### ISSUE TITLE
Request to sound with same URL should be mutualized

### ISSUE THREAD

**Issue by myagoo** [joshwcomeau/use-sound#11]
If I have a component wich `useSound('./test.wav')`, and this component is repeated many times, then multiple request are made for the sound

![image](https://user-images.githubusercontent.com/1036356/79068732-5f751200-7cc9-11ea-97cf-f50f01da869a.png)

**Comment by myagoo** [comment]
A workaround is to provide each sound that will be used from a single Provider.

A fix could be to maintain a global map `{[url: string]:  {sound: Howl, consumerCount: number}`.
This way you could only instanciate a new howl if the url ha snever been encountered before.
`consumerCount` is here to help correctly destroy Howl instance (may be there is nothing to destroy 🤷‍♂️) when there is no more `useSound` interested in that url

**Comment by joshwcomeau** [comment]
My guess is that most browsers will cache this request; Is it possible you have the `disable cache` box ticked in your devtools?

I suppose it's up to the server to specify cache headers. But yeah, in most cases I can't imagine these requests would actually go through 🤔
