### ISSUE TITLE
forceSoundEnabled option is ambiguous

### ISSUE THREAD

**Issue by myagoo** [joshwcomeau/use-sound#12]
In order to implement a mute button, and given the current state of my component tree, I wanted to do the following as I expected `forceSoundEnabled` to be a forced version of `soundEnabled` :

```
const [play] = useSound('whatever.mp3', {soundEnabled: true})

play({
  forceSoundEnabled: false,
})
// Sound is played 😟
```

It appears that `forceSoundEnabled` only do something if soundEnabled is false (see: https://github.com/joshwcomeau/use-sound/blob/master/src/index.ts#L91)

edit: The example here seems dumb since I call `play` with `forceSoundEnabled` set to `false`, in real life, `forceSoundEnabled` is computed from a prop.

**Comment by myagoo** [comment]
Workaround, do not call play if `soundEnabled === true` and call `play` with `forceSoundEnabled = true` when `soundEnabled === false`

```
if (!soundEnabled) {
  playToggle({
    forceSoundEnabled: true,
  })
}
```

**Comment by joshwcomeau** [comment]
Yeah, I added a comment in the PR, but my feeling is that you should avoid calling the play function if you know you don't actually want the sound to play; `playToggle({ forceSoundEnabled: false })` feels like an unnecessary call to me.

Going to close this, but let me know if I've missed something, will reopen it if I can get a better handle on the usecase!

**Comment by myagoo** [comment]
It's okay, it is just that I was misleaded by the forceSoundEnabled behavior. As you said, my only use case was for the mute toggle, and found another way (not callong play at all) to achieve the desired behavior 👍

**Comment by cassidoo** [comment]
Commenting to agree that I also felt misled here! I'd love to have some clarification around it, or even an example, especially for the mute button case.
