### ISSUE TITLE
Is it possible to rewind sound

### ISSUE THREAD

**Issue by fxckfallen** [joshwcomeau/use-sound#141]
i want to add scrollbar time control like this:
![image](https://github.com/joshwcomeau/use-sound/assets/121164875/86226cb1-f5ae-4d94-8f75-86d9a4909a1b)

**Comment by joshwcomeau** [comment]
Sorry for the delay — For advanced use cases like this, I'd use Howler directly. `use-sound` isn't really intended for more than playing a handful of sound effects.
