### ISSUE TITLE
Sound is NOT working in MOBILE devices

### ISSUE THREAD

**Issue by DinhKhai0201** [joshwcomeau/use-sound#142]
In desktop, sounds are working, 
but when I check on mobile devices (Chrome, Safari), sounds are not working. 

Here is the website: https://my-valentinee.vercel.app

**Comment by goritm** [comment]
Same here. Seems to be an [issue](https://stackoverflow.com/questions/77923783/audiocontext-failed-to-resume-in-ios-safari-17-4-beta-invalidstateerror-failed) with Webkit.

**Comment by jmalinkiewicz** [comment]
If you're using an iphone make sure your device isn't in silent mode

**Comment by joshwcomeau** [comment]
Yeah, mobile sound is always a bit tricky. It's beyond the scope of this library, I'd suggest opening any issues with reproducible test cases on Howler.
