### ISSUE TITLE
Howler Bug: The provided value is non-finite -> Please update Howler

### ISSUE THREAD

**Issue by codingyourlife** [joshwcomeau/use-sound#143]
I ran into this error:
TypeError
The provided value is non-finite

I found this howler bug:
https://github.com/goldfire/howler.js/issues/985

It is solved and merged here:
https://github.com/goldfire/howler.js/commit/e0343aa3f70779d473bf55010fd3b2f03f242571

It shows version: v2.2.4

We had a major sideeffect which was likely due to this internal crash.

**Please update howler**

**Comment by rnystrom** [comment]
@codingyourlife we have this same crash. The fix you linked to is from 2018 while howler 2.2.4 was released in September of 2023. I assume the linked fix is already included.

**Comment by joshwcomeau** [comment]
Howler is listed as a peer dependency, and it'll be happy with any 2.x version. It should automatically install the latest version when doing an initial install; after that, whichever version was selected will be added to your lockfile, so you'll have to upgrade it manually (eg. `npm install howler@latest`)
