### ISSUE TITLE
Could not find a declaration file for module 'use-sound'.

### ISSUE THREAD

**Issue by gabriel-logan** [joshwcomeau/use-sound#145]
![image](https://github.com/joshwcomeau/use-sound/assets/96627244/b80ffd28-f833-4af7-9f1c-305819b18247)

**Comment by git-ashwinpandey** [comment]
in your tsconfig.json,
change module resolution from bundle to node

"moduleResolution": "node",

**Comment by AashirBhusal** [comment]
create global.d.ts file in your root directory and write this 

declare module 'use-sound' {
    export default function useSound(sound: any, options?: any): any;
  }

**Comment by gabriel-logan** [comment]
> create global.d.ts file in your root directory and write this
> 
> declare module 'use-sound' { export default function useSound(sound: any, options?: any): any; }

My friend, if I wanted to use any I wouldn't use typescript.

**Comment by gabriel-logan** [comment]
The solution is: Either the devs come here and say what the correct typing is or they correct the declaration files in the library
