### ISSUE TITLE
Update sound url on user interaction 

### ISSUE THREAD

**Issue by domitriusclark** [joshwcomeau/use-sound#16]
Was wondering if there was a way to set the URL of `useSound` after render. I'm currently able to do it by creating a wrapper to pass down the url when I get it from cloudinary

Was thinking something like --

```jsx
export default function SoundButton({ audio }) {
  // data returns the url from cloudinary after sending the public ID in the useEffect
  const [getAudio, data] = useAudio({ cloud_name: 'your-cloud-name' });

  React.useEffect(() => {
    // before this runs, useSound will take in the initial "undefined" value of data
    // if you pass it immediately, thus not being able to do anything
    getAudio({
      public_id: audio
    });
  }, []);

  // send no audio initially
  const [play] = useSound()


  // play(data) performs some type of update to useSound to reinitialize -- possibly a deps arr instead??
  // couple options for the API
  return <button onClick={() => play(data)}>Play</button>
}
```

Happy to help if this sounds possible! Thanks again for this hook, totally jazzed me to create my personal site finally.

**Comment by domitriusclark** [comment]
Hmmm I actually think that's already a thing since you listen for changes to the URL, so I just plopped a `setState` before `play`

```jsx
export default function GameIconButton({ icon, audio }) {
  const [getAudio, data, status] = useAudio({ cloud_name: 'testing-hooks-upload' });
  const [url, setUrl] = React.useState("");

  React.useEffect(() => {
    getAudio({
      public_id: "game-sounds/switch"
    });
  }, []);

  const [play] = useSound(url)

  if (status === "loading") return <p>Loading...</p>;

  return (
    <React.Fragment>
      <Icon
        cursor="pointer"
        name={icon}
        size="xs"
        onClick={() => {
          setUrl(data)
          play()
        }} />
    </React.Fragment>
  )
}
```

**Comment by joshwcomeau** [comment]
Sorry for the delay on this @domitriusclark!

Yeah, you beat me to it; it listens for changes so as long as the URL is driven by state, it'll update.

Kind of a shame that it requires setting state only for the hook... but I think this is the best overall solution (briefly considered letting it expose a callback to call when a sound is loaded, but that complicates a bunch of stuff, and I like using the React render loop as the "source of truth" for this)

**Comment by domitriusclark** [comment]
I agree, once I checked in the code on round two it made sense. 

Maybe could use an example in the documentation?
