### ISSUE TITLE
isPlaying does not work correct

### ISSUE THREAD

**Issue by fxOne** [joshwcomeau/use-sound#19]
I'm starting the sound on page load directly:
```js
const [play, {stop, isPlaying}] = useSound(filePath);
  useEffect(() => {
    play();
    return () => {
      stop();
    };
  }, [play, stop]);
console.log(isPlaying)
```

`isPlaying` is logging at some point true even if there is no sound playing as the `play()` set the `isPlaying` always to true.
https://github.com/joshwcomeau/use-sound/blob/bbb8536e9c66faea1d9f368579cbdec06f68eb09/src/index.ts#L115
In the chrome console is seee the following error: `The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page.`.

My current workaround is to use the events from howler which looks to work fine:

```js
const [isPlaying, setIsPlaying] = useState(false);
const [, {sound}] = useSound(filePath);
useEffect(() => {
  sound?.on('play', () => setIsPlaying(true));
  sound?.on('stop', () => setIsPlaying(false));
  sound?.on('end', () => setIsPlaying(false));
  sound?.on('pause', () => setIsPlaying(false));
}, [sound]);
```

**Comment by imshuffling** [comment]
Thanks @fxOne this solved my issue of stopping the sound clip on route change.

```
  useEffect(() => {
    return () => {
      stop();
    };
  }, [stop]);
```

**Comment by joshwcomeau** [comment]
I ditched this property in 4.x

**Comment by mystrdat** [comment]
@joshwcomeau So what is the recommended mechanism to get the play state?
