### ISSUE TITLE
The AudioContext was not allowed to start

### ISSUE THREAD

**Issue by feross** [joshwcomeau/use-sound#22]
I get a warning on page load even when I haven't actually called `play()` yet. It seems like this is an issue in howler because they call `new AudioContext()` immediately.

Is it possible to somehow workaround this in `use-sound`?

**Comment by joshwcomeau** [comment]
Hm that's a bummer :/

For context: initially (before this repo existed) I created a `useSound` hook that did everything from scratch, and I couldn't get rid of that warning. I needed to create an AudioContext to be able to pre-emptively load the sound, otherwise there would be a delay when `play` was called. The warning was a small price to pay for no-latency.

When I switched to Howler, the warning disappeared, so I figured they knew something I didn't 🤷🏻‍♂️

Unfortunately I don't see much of a workaround (though I'd accept PRs if anyone has ideas that don't compromise the user experience!)

**Comment by techieeliot** [comment]
+1 I'm also getting this error @joshwcomeau.  I'm having issues playing the audio correctly, also.

**Comment by andrewmclagan** [comment]
We ended up rolling our own Howler hooks due to this issue. We came up with an elegant solution: Simply waiting for user interaction as the error states.

First need a hook that tracks first user interaction events according to the specs:

```javascript
import { useEffect, useState } from 'react';

const events = ['mousedown', 'touchstart'];

export default function useInteraction() {
  const [ready, setReady] = useState(false);

  const listener = () => {
    if (ready === false) {
      setReady(true);
    }
  };

  useEffect(() => {
    events.forEach((event) => {
      document.addEventListener(event, listener);
    });

    return () => {
      events.forEach((event) => {
        document.removeEventListener(event, listener);
      });   
    };
  }, []);

  return ready;
}
```

Then we wrapped howler in a simple async dynamic import hook that only loads it:
```javascript
import { useState, useEffect } from 'react';
import useInteraction from '../useInteraction';

export default function useAudio(options) {
  const [audio, setAudio] = useState();

  const interacted = useInteraction();

  useEffect(() => {
    async function createAudoContext() {
      const { Howl } = await import('howler');
      setAudio(new Howl(options));
    }

    if (interacted) {
      createAudoContext();
    }

    return () => {
      if (audio) {
        audio.unload();
      }
    };
  }, [options]);

  const ready = Boolean(interacted && audio);

  return { audio, ready };
}
```

All this in only a few Kb of js. Simple.

**Comment by LandonSchropp** [comment]
@andrewmclagan I really like your guys' solution, but I ran into some issues with it. For some reason, using the hook was causing infinite looping for me. I also found that I didn't need to load Howler asynchronously—I didn't see the `AudioContext` warning when importing it directly. Finally, I changed the API a bit to suit my personal use case.

Here's my modified version of your `useAudio` hook.

``` js
import { Howl } from "howler";
import { useEffect, useRef } from "react";

import useInteraction from "./use-interaction";

export default function useAudio(soundPath) {
  const hasInteracted = useInteraction();
  const audioRef = useRef();

  useEffect(() => {
    if (!hasInteracted) {
      return;
    }

    let audio = new Howl({ src: soundPath });
    audioRef.current = audio;

    return () => audio.unload();
  }, [ hasInteracted, soundPath ]);

  return () => audioRef.current?.play();
}
```

**Comment by joshwcomeau** [comment]
Hm, so it seems like Howler / the audio file are only loaded after the user interacts with the page?

I'd rather pre-load everything so that the sound can be triggered the moment the user interacts with the page. 

As annoying as the console warning is, I think that's the better trade-off here

**Comment by ryan-sirka** [comment]
> ```js
> .current?.play()
> ```

hello sir, can i see full of your code to play audio?

**Comment by PAXANDDOS** [comment]
I just bumped into this issue too, and I only needed some background music...

Your solutions @andrewmclagan @LandonSchropp worked just great! But then I went to the Howler API docs and found an even better way. Howler has its own "unlock" feature and can listen to the errors, this can be used to help us.

[See Howler's README](https://github.com/goldfire/howler.js#mobilechrome-playback)

And finally, my hook looks like that:
```ts
import { Howl } from 'howler'
import { useEffect, useState } from 'react'

import clown from '@assets/music/clown.mp3'

export const useMusic = () => {
    const [audio, setAudio] = useState<Howl | null>(null)

    useEffect(() => {
        const howl = new Howl({
            src: clown,
            onplayerror: (e, d) => {
                console.log(e, d)
                howl.once('unlock', () => {
                    howl.play()
                })
            },
            loop: true,
            volume: 0.25,
            autoplay: true,
        })
        setAudio(howl)

        return () => {
            howl.unload()
        }
    }, [])

    return [audio] as const
}
```
This still will create a bunch of warnings in the console, but works!

Note that I have `howler` required in my package.json so might need to do this too (plus `@types/howler` for typescript)

Linked issues:
goldfire/howler.js#1532
goldfire/howler.js#1287

**Comment by gio-shara-code** [comment]
@PAXANDDOS `onplayerror` does not even get triggered.

Still not able to manage playing audio on page initialization.

The audio only starts playing when I click on the page. (chrome detects gesture and therefore allows audio playing)

Any solutions to that in 2024?
