### ISSUE TITLE
How can i loop ?

### ISSUE THREAD

**Issue by AudereSemper** [joshwcomeau/use-sound#26]
Hello, there is a way to loop an mp3 ? 
I tried to see the documentation of Howler but i don't understand how to integrate it.

**Comment by TerryBerk** [comment]
Hey @AudereSemper, it's surprisingly easy enough, that's how it's done:

```
import mySound from './back.mp3'

export const App = () => {
  const [loopSound] = useSound(mySound, { loop: true });

  return(
    <div onClick={loopSound}>
    </div> 
  );
}
```

**Comment by AudereSemper** [comment]
man i really appreciate your work, so clean and simple :) really good job !

**Comment by claudiamatosa** [comment]
Hi there! I just arrived here. This library is really satisfying to use, thank you! Do you think it would make sense to add this to the typescript typings and docs or is it a side effect?

**Comment by mrbfrank** [comment]
OK now how do you loop & keep isPlaying state true?

```
import mySound from './back.mp3'

export const App = () => {
  const [loopSound, { stop, isPlaying }] = useSound(mySound, { loop: true });

  return(
    <div onClick={loopSound}>
    </div> 
  );
}
```
I have noticed that when looping, isPlaying returns false after the first loop ends!

**Comment by gp3098** [comment]
How can i increase the gap in the looping sound?

**Comment by mrbfrank** [comment]
@gp3098 I'd say either add silence to the end of your looping sound, or keep it a regular non-looping sound & run a timeout to re-trigger the sound when it stops playing. There should be some event or state change that indicates the end of playback, start your timeout when that happens.

**Comment by joshwcomeau** [comment]
++ to what @mrbfrank said
