### ISSUE TITLE
Question: How do I play multiple sounds on click of one button?

### ISSUE THREAD

**Issue by abhudaym** [joshwcomeau/use-sound#27]

**Comment by joshwcomeau** [comment]
Without a more concrete usecase it’s hard to understand exactly what you’re asking, but if you want to play multiple sounds concurrently, you have a few options:

- using audio editing software like Audacity, combine the sounds into a single sound
- set up multiple hooks, and trigger them all at the same time

For that second option, it would look something like this. Sorry for the lack of formatting, I’m on my phone. 

const [playSound1] = useSound(sound1Path);
const [playSound2] = useSound(sound2Path);

// later, in your JSX
<button onClick={() => {
  playSound1();
  playSound2();
}} />

**Comment by Gabsys** [comment]
When we are using 2 sounds, how can we determine the stop function for each sound?

**Comment by Matthewspear** [comment]
@Gabsys Just searching through issues on another problem, but I think you can access the ExposedData from the hook which contains the stop function:
```
const [playSound1, sound1] = useSound(sound1Path);
const [playSound2, sound2] = useSound(sound2Path);

sound1.stop();
sound2.stop();
```
