### ISSUE TITLE
Question: How capable is this?

### ISSUE THREAD

**Issue by rchrdnsh** [joshwcomeau/use-sound#4]
Not sure how to ask, but how far can one go with this hook? Could it power an entire music streaming application, like a Spotify style app, or is it really more geared toward a little sound effect here and there and nothing more? Just curious how you conceptualize it in your mind...it feels like the latter from your post, but I thought I’d ask you first before reaching any conclusions :-)

**Comment by joshwcomeau** [comment]
hey @rchrdnsh!

Yeah, so the intended usecase is definitely small sound effects. The kinds of stuff shown in the intro blog post.

That said, the hook is built around Howler, which is a super-capable audio library. And via escape hatches, you can do everything you can do with Howler.

So, I'd say that this hook is _probably_ capable of building an entire audio-focused application, but it's maybe not the best tool for the job :)

**Comment by tr1s** [comment]
@joshwcomeau do you know what tools are more capable of building entire audio-focused applications (in React), out of curiosity?

**Comment by joshwcomeau** [comment]
@tr1s I'd use the Web Audio API directly (this is what I do for [Beatmapper](https://beatmapper.app/)). You could also try using Howler directly, it's super powerful. Tie it into a Redux middleware and dispatch actions for every audio-related event.

Gonna close this now, but hopefully this helps!
