### ISSUE TITLE
to fix crashes with <sprite> 

### ISSUE THREAD

**Issue by constantinoPL** [joshwcomeau/use-sound#46]
you wrote in the example:

> To play a specific sprite, we'll pass its id when calling the play function:
> 
> <button
>   onClick={() => play('laser')}
> >

but must be onClick={() => play(**{ id: 'laser' }**)}

**Comment by martinjuhasz** [comment]
This is addressed in https://github.com/joshwcomeau/use-sound/pull/34 and will be fixed on an upcoming merge.

**Comment by joshwcomeau** [comment]
Sorry about that! Just merged the docs tweak.
