### ISSUE TITLE
Vanilla JS version?

### ISSUE THREAD

**Issue by mckeever02** [joshwcomeau/use-sound#54]
Hi, firstly... this is amazing! Really well done. Are there any plans to release a vanilla JS version that doesn't require React or some other framework? Would love to use this on a side-project I'm working on but it's non-react. 

Thanks

**Comment by TimSusa** [comment]
Hi,

as far as for my understanding the basic idea of this repo is to make use of React Hooks, so the requirement is essentially part of this. Maybe howler is more what you are searching for, because it is used here behind the Hooks facade. 

Cheers, 

Tim.

**Comment by mckeever02** [comment]
Hey!

Yeah I had a play with Howler and it's exactly what I was looking for. Thanks! Will close this issue.
