### ISSUE TITLE
Where is PlayButton from?

### ISSUE THREAD

**Issue by zoosm3** [joshwcomeau/use-sound#57]
Hi,

I would like to develop Play/pause button in the blog, but found no PlayButton in react-sound module.

https://www.joshwcomeau.com/react/announcing-use-sound-react-hook/

What module is this PlayButton from?

**Comment by TiemaCoulibaly** [comment]
Same here !!

**Comment by joshwcomeau** [comment]
Ah, I published it years ago here: https://github.com/joshwcomeau/react-play-button

Note that I haven't touched it in years, and I think I may have needed to modify something for that demo... I would copy/paste the code rather than install from NPM =)

Hope it helps!

**Comment by zoosm3** [comment]
Sounds nice! Thank you :)
