### ISSUE TITLE
Sounds are not working

### ISSUE THREAD

**Issue by alexhans1** [joshwcomeau/use-sound#58]
Something for some reason this lib has stopped working for me. 
Even in your demo on https://www.joshwcomeau.com/react/announcing-use-sound-react-hook/ many of the sounds are not working. Maybe something changed with some browser updates? Other than that I've only updated my react version.

**Comment by 0xdevalias** [comment]
@jknapp25 If you look in the JS console, are there any CORS related errors by chance?

**Comment by joshwcomeau** [comment]
Hm, not sure what's going on but it seems like an isolated usecase.
