### ISSUE TITLE
Sounds working locally but not after deploy

### ISSUE THREAD

**Issue by jknapp25** [joshwcomeau/use-sound#59]
My sounds are working locally, but not after I deploy...

Browser: Chrome
Setup: create-react-app
File formats: tried mp3 and m4a
File paths: relative
Stored in public directory?: no

**Comment by 0xdevalias** [comment]
@jknapp25 If you look in the JS console, are there any CORS related errors by chance?

**Comment by n1ru4l** [comment]
are the sounds triggered by user interaction? On mobile devices I had to add this "hack" for playing sound once a message is sent to the user. https://github.com/dungeon-revealer/dungeon-revealer/blob/master/src/register-sound-playback.tsx

**Comment by joshwcomeau** [comment]
My guess is that the files aren't able to be loaded somehow, maybe because the paths change in production.
