### ISSUE TITLE
Idea: Context provider for global sound enabling/disabling

### ISSUE THREAD

**Issue by Gvozd** [joshwcomeau/use-sound#6]
For use like this
```js
<SoundEnablingProvider enabled={true|false}>
  <ComponentWithSound />
</SoundEnablingProvider>
```

**Comment by joshwcomeau** [comment]
In fact, this is exactly what I do in my personal app! I have a `ConfigContext` which manages this, and then I built a very thin wrapper hook around `use-sound`:

```js
import React from 'react';
import useSoundBase from 'use-sound';

import { ConfigContext } from '@components/ConfigContext';

export default function useSound(url, delegated) {
  const { soundEnabled } = React.useContext(ConfigContext);

  return useSoundBase(url, { ...delegated, soundEnabled });
}
```

I think this is best solved in user-land, since that way you can tie it into whatever state-management solution you already use.

**Comment by AdrienLemaire** [comment]
@joshwcomeau I've added a wrapper as you suggested to toggle soundEnabled, but it doesn't seem to stop soundtracks, even with `{interrupt: true}`. What would be the appropriate way to auto-stop all playing sounds ?

**Comment by mutheus** [comment]
> In fact, this is exactly what I do in my personal app! I have a `ConfigContext` which manages this, and then I built a very thin wrapper hook around `use-sound`:
> 
> ```js
> import React from 'react';
> import useSoundBase from 'use-sound';
> 
> import { ConfigContext } from '@components/ConfigContext';
> 
> export default function useSound(url, delegated) {
>   const { soundEnabled } = React.useContext(ConfigContext);
> 
>   return useSoundBase(url, { ...delegated, soundEnabled });
> }
> ```
> 
> I think this is best solved in user-land, since that way you can tie it into whatever state-management solution you already use.

I could not make this work with Jotai. I would love to have this feature in my app.
