### ISSUE TITLE
Path for URL doesn't play sound unless I import it

### ISSUE THREAD

**Issue by hasibfox** [joshwcomeau/use-sound#62]
Hello!
Firstly, this appears to be such a wonderful tool. Thank you guys for developing it. My issue is that when I try to play a sound using the relative path (useSound('sound.mp3'), the sound does not play. When I import it on the top like "import sound from './sound.mp3', and useSound(sound), in that case, it works. I am planning to work with a few hundred audio clips so it's a bit messy to import every single one. I am also relatively new to React so I might be missing something. Any help would be awesome!

**Comment by joshwcomeau** [comment]
Yeah, I really need to add something about this to the docs. It really depends on how your application is structured.

• With Next.js, you can keep the files in `/public` and reference them the normal way
• Gatsby has a `/static` folder as well, I believe
• With create-react-app, I haven't personally tried it, but it looks like you can use PUBLIC_URL: https://create-react-app.dev/docs/using-the-public-folder/
