### ISSUE TITLE
Is this working on mobile?

### ISSUE THREAD

**Issue by shinyaK14** [joshwcomeau/use-sound#63]
Tutorial page's sound is working on Desktop. But it's not working on my iPhone. I cannot hear any sounds on mobile.

Is this a package only for desktop app?

Please correct me if I'm wrong.

https://www.joshwcomeau.com/react/announcing-use-sound-react-hook/

**Comment by Disfractal** [comment]
I'm trying to find the note but I thought I read that use-sound was for react DOM only and there's a different package for native.

**Comment by webdiego** [comment]
I've just developed a website, and it's working on mobile phone!

**Comment by joshwcomeau** [comment]
It should work on mobile, but there is that restriction that sounds won't play until the page has been interacted with. It's possible that the standards for "interaction" are slightly different between platforms.

**Comment by lucia-gomez** [comment]
> It should work on mobile, but there is that restriction that sounds won't play until the page has been interacted with. It's possible that the standards for "interaction" are slightly different between platforms.

How should we interact with the tutorial website (https://www.joshwcomeau.com/react/announcing-use-sound-react-hook/) to make the sound work on mobile? It works for me on desktop but I don't hear anything on mobile. Asking because use-sound is working in my own project on desktop, but not mobile.
