### ISSUE TITLE
Sounds not playing if there is embedded video meeting (or other WebRTC)

### ISSUE THREAD

**Issue by xpluscal** [joshwcomeau/use-sound#67]
In certain cases the audio doesn't play when there is an embedded (iFrame) application that uses video/audio capabilities.
Any experience with those issues?

In this case we are using jitsi's iFrame API

**Comment by joshwcomeau** [comment]
My hunch is that this is a browser/OS limitation, but I could be wrong 🤔 

I defer all audio stuff to [Howler](https://howlerjs.com/), you may have more luck asking that community.

Hope you can find a workaround!

**Comment by joshwcomeau** [comment]
(Closing since it's not something in this project's purview, not because it's unimportant.)

**Comment by xpluscal** [comment]
@joshwcomeau actually, the issue I discovered might be interesting.
I looked into this a bit more and it turns out, that even if a button was pressed by a user, the audio won't play (due to chrome restriction). So even if the user has pressed a button, sounds won't reappear. It actually only works if there has been some text input before. The curious thing is that button presses do not count. Do you have any ideas on how to solve that?
