### ISSUE TITLE
Sound played with delay on phone 

### ISSUE THREAD

**Issue by webdiego** [joshwcomeau/use-sound#68]
**Sound played with delay on phone** 

I noticed that the sound is reproduced perfectly, at the right times on the PC; on the contrary on smartphones it is reproduced with a slight delay.

**Comment by joshwcomeau** [comment]
Yeah, so I've heard that Android phones in particular have wildly-inconsistent audio latency, sometimes on the order of hundreds of milliseconds.

I don't think that this is a problem that can be solved in JS. If it could be, I imagine that Howler (the dependency I'm using for the actual audio playback) would have solved it by now =(

**Comment by webdiego** [comment]
I hope someday it settles down.
Thanks josh for the explanation and for this beautiful tool! :)
