### ISSUE TITLE
Can't use in a bundle made by webpack

### ISSUE THREAD

**Issue by Ofer-Gal** [joshwcomeau/use-sound#69]
Webpack is complaining:
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders

Any Idea what I can do?

**Comment by BrunoSette** [comment]
Are you using nextjs? I had the same problem. If so, you can try this solution: https://github.com/vercel/next.js/discussions/12810

**Comment by joshwcomeau** [comment]
I added some more info about this to the README: https://github.com/joshwcomeau/use-sound#importingsourcing-audio-files

Hope it helps!

**Comment by Ofer-Gal** [comment]
Thank you
