### ISSUE TITLE
3.0.0 breaks saying "Must use import to load ES Module"

### ISSUE THREAD

**Issue by KarandikarMihir** [joshwcomeau/use-sound#73]
<details>
<summary>Full error in Next.js (10.1.3)</summary>

```
Server Error
Error: Must use import to load ES Module: /Users/path/to/node_modules/use-sound/dist/index.js
require() of ES modules is not supported.
require() of /Users/path/to/node_modules/use-sound/dist/index.js from /Users/path/to/.next/server/pages/landing.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/path/to/node_modules/use-sound/package.json.
```
</details>

FWIW:
It starts working as expected when I remove `"type": "module"` from the package.json

**Comment by joshwcomeau** [comment]
Hm, can you share the code that uses this package?

Based on the error, I'm thinking you might be able to convert require to import:

```diff
-const useSound = require('use-sound');
+import useSound from 'use-sound';
```

Alternatively, you can also use v2, which doesn't have this field. Or, you can copy the code right into your project =) it's a relatively straightforward package, the two main files are [index.ts](https://github.com/joshwcomeau/use-sound/blob/master/src/index.ts) and [useOnMount.ts](https://github.com/joshwcomeau/use-sound/blob/master/src/use-on-mount.ts)

**Comment by joshwcomeau** [comment]
Ah, hm. I tested this on my own Next project and it seemed to work, but I see that I get the same error when I try to build, presumably because it converts the `import` statements to `require`.

@jlengstorf let me know if you have any ideas for this, I haven't kept up with module stuff. Thinking for now I'll revert this change

**Comment by KarandikarMihir** [comment]
@joshwcomeau Hey thanks for getting back. I was using `import` syntax with 3.0. I downgraded to 2.2.0 and it started working as expected. Thought I should give a heads up.

**Comment by joshwcomeau** [comment]
Yeah, I'm just gonna revert this change. Really frustrated that the module system is such a mess in JS :/

**Comment by joshwcomeau** [comment]
`3.0.1` removes the `type: module` field from package.json. I tested on my own Next project and it built, but feel free to let me know if you run into anything else
