### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by AdrienLemaire** [joshwcomeau/use-sound#74]
Hi,

Could you add release notes to explain the changes in versions?
Also, [npm](https://www.npmjs.com/package/use-sound) is listing use-sound at v3.0.1, but your master branch is still at v2.1.1, this is a bit confusing. Could you explain your versioning strategy if not following semver ?

Thanks for maintaining this package, it's great!

**Comment by ericblade** [comment]
Came here to ask this. I don't see a 3.0.x commit, but was surprised to see a 3.0.1 in npm

**Comment by joshwcomeau** [comment]
Must've forgotten to push the commit that published 3x. Just published 4.0 and I made sure to push the commit here as well.

Release notes would be helpful, but I'm trying to keep friction as low as possible. I don't have that much bandwidth to spare for this project.

**Comment by ericblade** [comment]
Cool :-) at least with the commits we can look at what changed :) Thank you!
