### ISSUE TITLE
Works in local not in Amplify Deployment

### ISSUE THREAD

**Issue by lvillacin** [joshwcomeau/use-sound#77]
It does not work after I deploy my react application but it works fine in local.

I use use-sound from within a useEffect as it looks at an array of messages.

What do I do?

**Comment by joshwcomeau** [comment]
Afraid I'm not sure, and I don't have the bandwidth to offer support. Sorry!

**Comment by johnjoshuadablo** [comment]
@lvillacin Have you found a workaround on this ?

**Comment by johnjoshuadablo** [comment]
Found the solution.

https://stackoverflow.com/questions/66835474/audio-tag-not-working-in-reactjs-application-deployed-in-aws-amplify


You need to add an mp3 file extension to your application's URL rewrites in Amplify.

In your app's homepage in Amplify click on 'Rewrites and redirects' under App Settings. Then click edit and add mp3 to the list of extensions in your rewrite rule.

It'll probably look something like this after you add it:

`</^[^.]+$|\.(?!(css|gif|ico|jpg|jpeg|js|png|mp3|txt|svg|woff|ttf|map|json)$)([^.]+$)/>`
