### ISSUE TITLE
Loops?

### ISSUE THREAD

**Issue by elron** [joshwcomeau/use-sound#78]
Are loops possible?
How?

**Comment by ThomasRutzer** [comment]
yep, you can just pass it initially: 
`  const [play] = useSound(url, { volume, loop: true })`

Additionally Howler options are [delegated](https://github.com/joshwcomeau/use-sound/blob/master/src/index.ts#L50)

**Comment by elron** [comment]
Thanks so much!

**Comment by ThomasRutzer** [comment]
you're welcome! Don't forget to close if its done.
