### ISSUE TITLE
Storybook does not work

### ISSUE THREAD

**Issue by marcofugaro** [joshwcomeau/use-sound#79]
I've opened storybook from the link in the README and this is what I see

https://use-sound.netlify.app/

![image](https://user-images.githubusercontent.com/7217420/118970642-bdfdcc80-b96e-11eb-835b-5dc4ee9e7cf7.png)

**Comment by joshwcomeau** [comment]
Hm, it seems to be working for me now. Maybe this was a Netlify hiccup?

<img width="1074" alt="CleanShot 2021-06-04 at 13 00 15@2x" src="https://user-images.githubusercontent.com/6692932/120837549-d1936080-c534-11eb-8da1-ea5a68c59e12.png">


Let me know if you still don't see the page.

**Comment by marcofugaro** [comment]
It works now!
